name: CI

on:
  pull_request:
    paths-ignore:
    - '**/*.md'
  push:
    paths-ignore:
    - '**/*.md'

# See the blog post here for some additional examples with building
# Arduino on GitHub actions (e.g. building for multiple platforms):
# https://blog.arduino.cc/2019/11/14/arduino-on-github-actions/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1.1.1
    - uses: actions/checkout@v2
    - name: Build sketch
      run: make all
