name: CI

on:
  pull_request:
    paths-ignore:
    - '**/*.md'
  push:
    paths-ignore:
    - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1.1.1
    - uses: actions/checkout@v2
    - name: Build sketch
      run: make all
